# Numpy 학습

### 1. Numpy ndarray 개요

In [1]:
import numpy as np

#### 1) ndarray 배열의 차원

In [2]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
# ndarry 차원 확인
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim,
                                                             array2.ndim, array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원


### 2. ndarray의 데이터 타입

#### 1) 데이터 타입

- 모든 타입 가능 (int, bool, float, char 등등...)
- 하나의 ndarray 객체에는 하나의 타입끼리만 공존 가능
- 다른 데이터 유형이 섞여있을 경우 -> 더 큰 데이터 타입으로 형 변환 일괄 적용

In [6]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

#데이터 타입 변환 예제
list2 = [1,2,'hey']
array2 = np.array(list2)
print(array2, array2.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
['1' '2' 'hey'] <U11


- astype() 메서드 => ndarray 내 타입 변경 가능

### 3. ndarray를 편리하게 생성하기 - arange, zeros, ones

#### 1) arange() 함수

- range()와 유사 기능
- 0 ~ n-1 까지의 값을 순차적으로 데이터값으로 변환

In [7]:
s_array = np.arange(10)
print(s_array)
print(s_array.dtype, s_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


#### 2) zeros(), ones() 함수

- 튜플 형태의 shape 값 입력
      => zeros() : 모든 값을 0으로 채운 해당 shape의 ndarray 반환
      => ones() : 모든 값을 1로 채운 해당 shape의 ndarray 반환

In [8]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### 4. ndarray의 차원과 크기를 변경하는 reshape()

- ndarray를 특정 차원 / 크기로 변환

In [10]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


- 지정된 사이즈로 변경 불가 시 오류 발생

In [12]:
#오류 발생
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

NameError: name 'array3d' is not defined

- 인자로 -1 적용 시 원 ndarray와 호환되는 새로운 shape로 변환해줌
- 그래도 불가능한 형태로는 변환 불가

In [13]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 5. 넘파이의 ndarray의 데이터셋 선택하기 - 인덱싱(Indexing)

1. 특정 데이터만 추출
2. Slicing : 연속된 인덱스 상의 ndarray를 추출하는 방식
3. Fancy Indexing : 일정한 인덱싱 집합을 list or ndarray 형태로 지정, 반환
4. Boolean Indexing : 특정 조건의 True에 해당하는 인덱스 위치의 데이터 반환

#### 1) 단일 값 추출

In [15]:
# 1차원 배열
a1 = np.arange(start=1, stop=10)
print('a1:', a1)

value = a1[2]
print('value:', value)
print(type(value))

#2차원 배열도 동일 [x, y] 형식으로 접근

a1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


#### 2) Slicing

- 연속된 인덱스 상의 ndarray를 추출하는 방식
- 기호 ':' 사용

In [19]:
#1차원 배열
a1 = np.arange(start=1, stop=10)
a3 = a1[0:3]
print(a3)
print(type(a3))

print(a1[:3])
print(a1[3:])
print(a1[:])

#2차원 배열에서도 동일 방식 사용

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


#### 3) Fancy Indexing

- 일정한 인덱싱 집합을 list or ndarray 형태로 지정, 반환
- 직사각형 모양의 칸을 잡을 때 유리한 듯!

In [20]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] =>', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


#### 4) Boolean Indexing

- 특정 조건의 True에 해당하는 인덱스 위치의 데이터 반환

In [21]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과값:', array3)

array1d > 5 불린 인덱싱 결과값: [6 7 8 9]


### 6. 행렬의 정렬 - sort()와 argsort()

#### 1) sort()

- np.sort() 방식 : 원행렬 유지, 정렬값만 도출
- ndarray.sort() 방식 : 원행렬을 정렬한 상태로 변경

#### 2) argsort()

- 원본 행렬 정렬 시 정렬 전 인덱스 순서를 정렬 후 순서대로 반환

### 7. 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

#### 1) 행렬 내적 (행렬 곱)

In [24]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])

#내적 결과값 = dot_p
dot_p = np.dot(A,B)
print(dot_p)

[[ 58  64]
 [139 154]]


#### 2) 전치 행렬

In [25]:
A = np.array([[1,2],
              [3,4]])

#전치행렬 t_mat
t_mat = np.transpose(A)
print(t_mat)

[[1 3]
 [2 4]]
